sip:
  account: "169532"  # SIP账户
  server: "159.138.145.85"                 # SIP服务器地址
  username: "169532"                       # SIP用户名
  password: "wangchuan123"                 # SIP密码
  port: 62060                              # SIP端口
  transport: "UDP"                         # 传输协议
  register_refresh: 300                    # 注册刷新时间（秒）
  keep_alive: 15                          # 保活时间（秒）
  target_number: "13001413111"
  #bind_ip: "0.0.0.0"  # 可选
  #bind_port: 5060
  voice_file: "initial_message.wav"       # 语音文件路径
  tts_text: "您好, 我是九一的客服小微,您已获取得系统返还的100元的奖金,请您登录九一软件领取,有效时间30天"
  tts_voice: "zh-CN-XiaoxiaoNeural"

call:
  list_file: "tel.txt"  # 电话号码列表文件，每行一个号码
  log_file: "call_log.csv"  # 呼叫记录日志
  interval: 5  # 两次呼叫之间的间隔时间(秒)

whisper:
  model_size: "small"  # 可选: tiny, base, small, medium, large
  model_dir: "models/whisper"

responses:
  greeting: "您好，我是AI助手，很高兴为您服务。"
  interested: "感谢您的兴趣，我们的产品具有以下特点..."
  not_interested: "感谢您的时间，祝您生活愉快。"
  default: "抱歉，我没有听清楚，请您再说一遍。" 