sip:
  account: "169532@159.138.145.85:62060"  # SIP账户
  server: "159.138.145.85:62060"          # SIP服务器地址
  username: "169532"                       # SIP用户名
  password: "wangchuan123"                 # SIP密码
  port: 62060                              # SIP端口
  transport: "UDP"                         # 传输协议
  register_refresh: 300                    # 注册刷新时间（秒）
  keep_alive: 15                          # 保活时间（秒）

call:
  initial_message: "initial_message.wav"   # 初始语音文件
  response_timeout: 5                      # 等待用户响应时间（秒）
  target_number: "sip:target_number@159.138.145.85:62060" # 目标电话号码

responses:
  greeting: "您好，我是AI助手，很高兴为您服务。"
  interested: "感谢您的兴趣，我们的产品具有以下特点..."
  not_interested: "感谢您的时间，祝您生活愉快。"
  default: "抱歉，我没有听清楚，请您再说一遍。" 