sip:
  account: "169532"  # SIP账户
  server: "159.138.145.85"                 # SIP服务器地址
  username: "169532"                       # SIP用户名
  password: "wangchuan123"                 # SIP密码
  port: 62060                              # SIP端口
  transport: "UDP"                         # 传输协议
  register_refresh: 300                    # 注册刷新时间（秒）
  keep_alive: 15                          # 保活时间（秒）
  target_number: "13216600657"
  voice_file: "initial_message.wav"  # 语音文件路径


responses:
  greeting: "您好，我是AI助手，很高兴为您服务。"
  interested: "感谢您的兴趣，我们的产品具有以下特点..."
  not_interested: "感谢您的时间，祝您生活愉快。"
  default: "抱歉，我没有听清楚，请您再说一遍。" 