sip:
  account: "169532"  # SIP账户
  server: "159.138.145.85"                 # SIP服务器地址
  username: "169532"                       # SIP用户名
  password: "wangchuan123"                 # SIP密码
  port: 62060                              # SIP端口
  transport: "UDP"                         # 传输协议
  register_refresh: 300                    # 注册刷新时间（秒）
  keep_alive: 15                          # 保活时间（秒）
  #bind_ip: "0.0.0.0"  # 可选
  #bind_port: 5060、

call:
  list_file: "conf/tel.txt"      # 电话号码列表文件，每行一个号码
  log_file: "log/call_log.csv"   # 呼叫记录日志
  interval: 5  # 两次呼叫之间的间隔时间(秒)

whisper:
  model_size: "turbo"  # 可选: tiny, base, small, medium, large, turbo
  model_dir: "models/whisper"
